import { Inter } from "next/font/google";
import "./globals.css";
import Headers from "./components/Headers";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Origin Dog-udemy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className='sm:bg-orange-300 md:bg-pink-300 lg:bg-blue-300 xl:bg-green-300 '>
        <Headers/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
